version: "3.9"
services:
  api:
    container_name: api_container
    env_file:
      - .env
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - './:/code'

  db:
    container_name: db_container
    image: postgres:15.2
    ports:
      - "5432:5432"
    env_file:
      - .env